### ISSUE TITLE
03_data_types/03_characters.md ASCII chart

### ISSUE THREAD

**Issue by BroBQ** [Xeverous/Xeverous.github.io#16]
I suggest mentioning ASCII was/is used in keyboards and printers (for example carriage return), as a way how devices can communitace (for better understanding).
As well adding this ASCII chart
https://en.cppreference.com/w/cpp/language/ascii

**Comment by Xeverous** [comment]
Fixed in 980a587d2e2a0859273eeed2667c61bfdff484b8
