### ISSUE TITLE
/07_functions/01_basics.md syntax & function parts similarity

### ISSUE THREAD

**Issue by BroBQ** [Xeverous/Xeverous.github.io#25]
Those two sections (syntax & function parts) cover the same thing. First part explain basics and then in second part it is explained further. Please consider merging them together.

I am not sure but there should be information that reader already should know one function, it's int main()

It should be explained just in few words:
`std::cout << f(f(f(3))) << "\n"; `

your*
Hint: use a helper function inside - you own or std::abs().

**Comment by Xeverous** [comment]
All already mentioned and/or fixed in d73d9061dc64b46828e8877e828a767140917663.
